#!/usr/bin/env node


'use strict'

var c = require("skilstak-colors");

                
                
console.log(c.clear + c.multi("This is where people make important decisions like if Grumpy Cat still needs a youtube acount, it is always a yes.")); 
 

